INSERT INTO vehiculos (marca, modelo, precio, anio, kilometros, combustible, plazas, descripcion, imagen_url)
VALUES
(
'PEUGEOT',
'Boxer L1H2',
17500,
2015,
84000,
'Diésel',
3,
'Esta web utiliza cookies para que podamos ofrecerte la mejor experiencia de usuario posible. La información de las cookies se almacena en tu navegador y realiza funciones tales como reconocerte cuando vuelves a nuestra web o ayudar a nuestro equipo a comprender qué secciones de la web encuentras más interesantes y útiles.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
),
(
'VOLKSWAGEN',
'Crafter L2H2',
20990,
2017,
125000,
'Diésel',
3,
'Si buscas una furgonetapremium para trabajar a diario o camperizar con garantías, estaVolkswagen Crafter L2H2es una apuesta segura. Potente, cómoda y muy equipada.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
),
(
'FORD',
'Transit L1H1',
14890,
2014,
160000,
'Diésel',
3,
'Se vendeFord Transit Custom L1H1 año 2014, una furgoneta compacta, fiable y muy versátil, ideal para trabajo diario, reparto urbano o proyecto camper compacto.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
),
(
'CITROEN',
'Jumper L2H2',
11990,
2013,
220000,
'Diésel',
3,
'Se vendeCitroën Jumper L2H2 año 2013, una furgoneta fiable y muy cuidada, perfecta tanto para trabajo diario como para proyecto camper.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
),
(
'FIAT',
'Ducato L2H2',
17000,
2016,
130000,
'Diésel',
3,
'Esta web utiliza cookies para que podamos ofrecerte la mejor experiencia de usuario posible. La información de las cookies se almacena en tu navegador y realiza funciones tales como reconocerte cuando vuelves a nuestra web o ayudar a nuestro equipo a comprender qué secciones de la web encuentras más interesantes y útiles.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
),
(
'PEUGEOT',
'Boxer L2H2',
15500,
2016,
200000,
'Diésel',
3,
'Esta web utiliza cookies para que podamos ofrecerte la mejor experiencia de usuario posible. La información de las cookies se almacena en tu navegador y realiza funciones tales como reconocerte cuando vuelves a nuestra web o ayudar a nuestro equipo a comprender qué secciones de la web encuentras más interesantes y útiles.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
),
(
'FORD',
'Transit Caja Abierta',
23800,
2018,
160000,
'Diésel',
3,
'Se vendeFord Transit caja abierta año 2018, una camioneta robusta y muy funcional, ideal para transporte de mercancía, obras y trabajos de gran volumen.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
),
(
'FIAT',
'Ducato L2H2',
20000,
2021,
169000,
'Diésel',
3,
'Parece que no podemos encontrar lo que estás buscando. Tal vez la búsqueda pueda ayudar.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
),
(
'FORD',
'Transit L3H2',
15000,
2016,
198000,
'Diésel',
3,
'Se vendeFord Transit L2H2 año 2016, una furgoneta fiable, espaciosa y muy versátil, perfecta tanto para uso profesional como para proyecto camper.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
),
(
'PEUGEOT',
'Boxer L2H2',
15500,
2015,
169000,
'Diésel',
3,
'Esta web utiliza cookies para que podamos ofrecerte la mejor experiencia de usuario posible. La información de las cookies se almacena en tu navegador y realiza funciones tales como reconocerte cuando vuelves a nuestra web o ayudar a nuestro equipo a comprender qué secciones de la web encuentras más interesantes y útiles.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
),
(
'PEUGEOT',
'Boxer L4H3',
21500,
2018,
155000,
'Diésel',
3,
'Se vendePeugeot Boxer L4H3 año 2018, una furgoneta de gran volumen, muy potente y extremadamente cuidada, ideal para trabajos de gran carga o proyecto camper de gran tamaño.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
),
(
'CITROEN',
'Jumper L3H2',
17500,
2015,
170000,
'Diésel',
3,
'Se vendeCitroën Jumper año 2015, una furgoneta potente, fiable y muy cuidada, perfecta tanto para uso profesional como para proyecto camper.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
),
(
'CITROEN',
'Jumper L1H1',
18990,
2018,
70000,
'Diésel',
3,
'Se vendeCitroën Jumper L1H1 año 2018, compacta, potente y muy cuidada, ideal para reparto urbano y trabajo diario.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
),
(
'PEUGEOT',
'Boxer L2H2',
16500,
2016,
125000,
'Diésel',
3,
'Esta web utiliza cookies para que podamos ofrecerte la mejor experiencia de usuario posible. La información de las cookies se almacena en tu navegador y realiza funciones tales como reconocerte cuando vuelves a nuestra web o ayudar a nuestro equipo a comprender qué secciones de la web encuentras más interesantes y útiles.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
),
(
'OPEL',
'Movano L2H2',
20000,
2020,
125000,
'Diésel',
3,
'Se vendeOpel Movano L2H2 año 2020, una furgoneta fiable, potente y muy cuidada, perfecta tanto para trabajo diario como para proyecto camper.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
),
(
'CITROEN',
'Jumper L2H2',
17000,
2014,
140000,
'Diésel',
6,
'Esta web utiliza cookies para que podamos ofrecerte la mejor experiencia de usuario posible. La información de las cookies se almacena en tu navegador y realiza funciones tales como reconocerte cuando vuelves a nuestra web o ayudar a nuestro equipo a comprender qué secciones de la web encuentras más interesantes y útiles.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
),
(
'RENAULT',
'Master L2H2',
16500,
2018,
160000,
'Diésel',
3,
'Esta web utiliza cookies para que podamos ofrecerte la mejor experiencia de usuario posible. La información de las cookies se almacena en tu navegador y realiza funciones tales como reconocerte cuando vuelves a nuestra web o ayudar a nuestro equipo a comprender qué secciones de la web encuentras más interesantes y útiles.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
),
(
'RENAULT',
'Master Basculante',
18900,
2013,
160000,
'Diésel',
3,
'Esta web utiliza cookies para que podamos ofrecerte la mejor experiencia de usuario posible. La información de las cookies se almacena en tu navegador y realiza funciones tales como reconocerte cuando vuelves a nuestra web o ayudar a nuestro equipo a comprender qué secciones de la web encuentras más interesantes y útiles.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
),
(
'FIAT',
'Ducato L4H3',
17000,
2017,
240000,
'Diésel',
3,
'Ponemos a la venta estaFiat Ducato L4H3con240.000 km, en unestado impecable, cuidada al detalle ycomo nueva.Una furgoneta amplia, fiable y potente, perfecta para profesionales que buscancapacidad, comodidad y confianzadesde el primer día.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
),
(
'CITROEN',
'Jumpy 6 Plazas',
13000,
2013,
178000,
'Diésel',
6,
'Esta web utiliza cookies para que podamos ofrecerte la mejor experiencia de usuario posible. La información de las cookies se almacena en tu navegador y realiza funciones tales como reconocerte cuando vuelves a nuestra web o ayudar a nuestro equipo a comprender qué secciones de la web encuentras más interesantes y útiles.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
),
(
'OPEL',
'Vivaro 6 Plazas',
21000,
2019,
100000,
'Diésel',
6,
'Esta web utiliza cookies para que podamos ofrecerte la mejor experiencia de usuario posible. La información de las cookies se almacena en tu navegador y realiza funciones tales como reconocerte cuando vuelves a nuestra web o ayudar a nuestro equipo a comprender qué secciones de la web encuentras más interesantes y útiles.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
),
(
'OPEL',
'Vivaro',
19800,
2019,
120000,
'Diésel',
3,
'Esta web utiliza cookies para que podamos ofrecerte la mejor experiencia de usuario posible. La información de las cookies se almacena en tu navegador y realiza funciones tales como reconocerte cuando vuelves a nuestra web o ayudar a nuestro equipo a comprender qué secciones de la web encuentras más interesantes y útiles.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
),
(
'FORD',
'Transit L3H3',
17500,
2016,
160000,
'Diésel',
3,
'Esta web utiliza cookies para que podamos ofrecerte la mejor experiencia de usuario posible. La información de las cookies se almacena en tu navegador y realiza funciones tales como reconocerte cuando vuelves a nuestra web o ayudar a nuestro equipo a comprender qué secciones de la web encuentras más interesantes y útiles.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
),
(
'PEUGEOT',
'Boxer L3H2',
20000,
2020,
150000,
'Diésel',
3,
'Esta web utiliza cookies para que podamos ofrecerte la mejor experiencia de usuario posible. La información de las cookies se almacena en tu navegador y realiza funciones tales como reconocerte cuando vuelves a nuestra web o ayudar a nuestro equipo a comprender qué secciones de la web encuentras más interesantes y útiles.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
),
(
'RENAULT',
'Master Caja Abierta',
18900,
2013,
160000,
'Diésel',
3,
'Esta web utiliza cookies para que podamos ofrecerte la mejor experiencia de usuario posible. La información de las cookies se almacena en tu navegador y realiza funciones tales como reconocerte cuando vuelves a nuestra web o ayudar a nuestro equipo a comprender qué secciones de la web encuentras más interesantes y útiles.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
),
(
'VOLKSWAGEN',
'Caravelle Batalla Larga',
27500,
2016,
203000,
'Diésel',
9,
'Parece que no podemos encontrar lo que estás buscando. Tal vez la búsqueda pueda ayudar.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
),
(
'CITROEN',
'Jumper L3H3',
22400,
2017,
108000,
'Diésel',
3,
'Esta web utiliza cookies para que podamos ofrecerte la mejor experiencia de usuario posible. La información de las cookies se almacena en tu navegador y realiza funciones tales como reconocerte cuando vuelves a nuestra web o ayudar a nuestro equipo a comprender qué secciones de la web encuentras más interesantes y útiles.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
),
(
'FIAT',
'Ducato L3H2',
19000,
2021,
190000,
'Diésel',
3,
'Esta web utiliza cookies para que podamos ofrecerte la mejor experiencia de usuario posible. La información de las cookies se almacena en tu navegador y realiza funciones tales como reconocerte cuando vuelves a nuestra web o ayudar a nuestro equipo a comprender qué secciones de la web encuentras más interesantes y útiles.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
),
(
'PEUGEOT',
'Boxer L2H2',
16500,
2017,
130000,
'Diésel',
3,
'Se vendePeugeot Boxer L2H2 año 2016, una furgoneta fiable y muy versátil, ideal tanto para trabajo diario como para camperización.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
),
(
'FIAT',
'Ducato L2H2',
19000,
2019,
130000,
'Diésel',
3,
'Se vendeFiat Ducato L2H2 año 2021, una de las furgonetas más demandadas por su fiabilidad, espacio y bajo consumo. Perfecta tanto para profesionales como para camperización.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
),
(
'OPEL',
'Vivaro',
21500,
2021,
125000,
'Diésel',
3,
'Esta web utiliza cookies para que podamos ofrecerte la mejor experiencia de usuario posible. La información de las cookies se almacena en tu navegador y realiza funciones tales como reconocerte cuando vuelves a nuestra web o ayudar a nuestro equipo a comprender qué secciones de la web encuentras más interesantes y útiles.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
),
(
'FIAT',
'Ducato L2H1',
19900,
2021,
130000,
'Diésel',
3,
'Esta web utiliza cookies para que podamos ofrecerte la mejor experiencia de usuario posible. La información de las cookies se almacena en tu navegador y realiza funciones tales como reconocerte cuando vuelves a nuestra web o ayudar a nuestro equipo a comprender qué secciones de la web encuentras más interesantes y útiles.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
),
(
'PEUGEOT',
'Boxer L2H2',
18500,
2020,
160000,
'Diésel',
3,
'Se vendePeugeot Boxer L2H2 año 2015, una furgoneta robusta, fiable y muy versátil, perfecta tanto para uso profesional como para proyecto camper.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
),
(
'PEUGEOT',
'Partner',
12990,
2018,
105000,
'Diésel',
2,
'Esta web utiliza cookies para que podamos ofrecerte la mejor experiencia de usuario posible. La información de las cookies se almacena en tu navegador y realiza funciones tales como reconocerte cuando vuelves a nuestra web o ayudar a nuestro equipo a comprender qué secciones de la web encuentras más interesantes y útiles.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
),
(
'RENAULT',
'Master L1H2',
17500,
2017,
150000,
'Diésel',
3,
'Esta web utiliza cookies para que podamos ofrecerte la mejor experiencia de usuario posible. La información de las cookies se almacena en tu navegador y realiza funciones tales como reconocerte cuando vuelves a nuestra web o ayudar a nuestro equipo a comprender qué secciones de la web encuentras más interesantes y útiles.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
),
(
'OPEL',
'Vivaro',
13498,
2016,
200000,
'Diésel',
3,
'Parece que no podemos encontrar lo que estás buscando. Tal vez la búsqueda pueda ayudar.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
),
(
'PEUGEOT',
'Boxer L3H2',
25800,
2023,
50000,
'Diésel',
3,
'Esta web utiliza cookies para que podamos ofrecerte la mejor experiencia de usuario posible. La información de las cookies se almacena en tu navegador y realiza funciones tales como reconocerte cuando vuelves a nuestra web o ayudar a nuestro equipo a comprender qué secciones de la web encuentras más interesantes y útiles.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
),
(
'OPEL',
'Movano L3H2',
26000,
2024,
40400,
'Diésel',
3,
'Esta web utiliza cookies para que podamos ofrecerte la mejor experiencia de usuario posible. La información de las cookies se almacena en tu navegador y realiza funciones tales como reconocerte cuando vuelves a nuestra web o ayudar a nuestro equipo a comprender qué secciones de la web encuentras más interesantes y útiles.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
),
(
'OPEL',
'Vivaro',
19500,
2019,
125000,
'Diésel',
3,
'Parece que no podemos encontrar lo que estás buscando. Tal vez la búsqueda pueda ayudar.',
'https://flexemcar.com.es/wp-content/uploads/2024/09/cropped-Logotipo_FlexemCar.png'
);